
server:
  port: 8000
 
spring:
  datasource:
    username: root
    password: 
    url: jdbc:mysql://localhost:3306/learnapp?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
 
mybatis:
  mapper-locations: classpath:com/ldhf/mapper/*.xml
  type-aliases-package: com.app.entity
 
#showSql
logging:
  level:
    com:
      example:
        mapper : debug